name: 'ispw-build'
description: 'Run a build in BMC Compuware ISPW'
branding:
  icon: activity
  color: orange
inputs:
  ces_url:
    description: 'The URL to send requests to.'
    required: true
  ces_token:
    description: 'The token to use when connecting to ISPW through CES'
    required: true
  srid:
    description: 'The ID for the instance of ISPW to connect to'
    required: true
  runtime_configuration:
    description: 'The runtime configuration used when connecting to ISPW'
    required: false
  assignment_id:
    description: 'The container for which you intend to build tasks.'
    required: false
  level:
    description: 'The level that the tasks exist at in the assignment'
    required: false
  task_id:
    description: 'The comma-separated list of task IDs for the tasks that need to be built'
    required: false
  build_automatically:
    description: 'The request parameters for the build will come from a file written to a local directory. This option is only valid when used in combination with a Git to ISPW Integration step'
    required: false
  change_type: 
    description: 'S for standard, I for incidental, or E for emergency. Default value of S'
    required: true
    default: 'S'
  execution_status:
    description: 'I for immediate execution or at start date/time, H to create request in hold'
    required: true
    default: 'I'
  auto_deploy:
    description: 'Build can be set up to automatically Deploy as well by an option set up by the ISPW. The default is to not use Auto Deploy. If the Auto Deploy option is set-up through ISPW, then you may use this option to automatically deploy instead of using the deployAutomatically option within the DeployTask/DeployAssignment/DeployRelease actions'
    required: true
    default: 'false'
outputs:
  failed_count:
    description: 'The number of tasks that failed to build'
  success_count:
    description: 'The number of tasks that built successfully'
  has_failures:
    description: 'Whether there were any build failures'
  is_timed_out:
    description: 'Whether the build timed out'
  task_count:
    description: 'The total number of tasks a build was initiated against'
  set_id:
    description: 'The ID of the set that was used for processing'
  url:
    description: 'The URL that can be used to retrieve information about the set that was used for processing'
runs:
  using: 'node12'
  main: 'dist/index.js'
